POST http://localhost:3010/api/auth/signup
content-type: application/json

{
    "username": "sample",
    "password": "sample"
}

###

POST http://localhost:3010/api/auth/login
content-type: application/json

{
    "username": "sample",
    "password": "sample"
}

###

GET http://localhost:3010/api/test/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDZmYWFkZWJmYWEzOGIzZmEzNmRkOSIsImlhdCI6MTY5MTgxMDQ4MCwiZXhwIjoxNjkxODk2ODgwfQ.oaEHq5u1dTkSdV-L659pKPwpe3w25iYCqJKROv21r6w