POST http://localhost:3010/api/auth/signup
content-type: application/json

{
    "username": "sample",
    "password": "sample"
}

###

POST http://localhost:3010/api/auth/login
content-type: application/json

{
    "username": "sample",
    "password": "sample"
}

###

GET http://localhost:3010/api/test/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDgxY2U0ODM4MzczODA2ZTljOTY4YSIsImlhdCI6MTY5MTg4NDc3NCwiZXhwIjoxNjkxOTcxMTc0fQ.liBWXcCC4cLAQPIdsDTif6FcZ6ItmSK-QCWFUBqqObY

###

GET http://localhost:3010/api/user/ledger
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDgxZDZiNzJkNzlhNDVhYzY5N2ZmYyIsImlhdCI6MTY5MTg4NDkxNywiZXhwIjoxNjkxOTcxMzE3fQ.u2wyY7DPE1rqzkq9WoZRWQb1icFZa6HEdsslUhrP4eg

###

GET http://localhost:3010/api/stocks/AAPL/info

###

GET http://localhost:3010/api/stocks/AAPL/historical